//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.ListOfGenres = new HashSet<ListOfGenre>();
            this.SaleOfTheGames = new HashSet<SaleOfTheGame>();
        }
    
        public int ID { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Издатель { get; set; }
        public Nullable<int> Разработчик { get; set; }
        public Nullable<int> Стоимость { get; set; }
        public byte[] Фото { get; set; }
    
        public virtual Bublisher Bublisher { get; set; }
        public virtual Creator Creator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListOfGenre> ListOfGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOfTheGame> SaleOfTheGames { get; set; }
    }
}
