//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfGenre
    {
        public int ID { get; set; }
        public Nullable<int> Жанр { get; set; }
        public Nullable<int> Игра { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
