//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlinePСGamesEntities : DbContext
    {
        public OnlinePСGamesEntities()
            : base("name=OnlinePСGamesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bublisher> Bublishers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Creator> Creators { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<ListOfGenre> ListOfGenres { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<SaleOfTheGame> SaleOfTheGames { get; set; }
    }
}
